extern u64 gPoisonedWaterDL_poisoned_water_base_texture_rgba16[];
extern Vtx gPoisonedWaterDL_actualwater_mesh_layer_Transparent_vtx_cull[8];
extern Vtx gPoisonedWaterDL_actualwater_mesh_layer_Transparent_vtx_0[4];
extern Gfx gPoisonedWaterDL_actualwater_mesh_layer_Transparent_tri_0[];
extern Gfx mat_gPoisonedWaterDL_f3d_material_layerTransparent[];
extern Gfx gPoisonedWaterDL[];
